// #define POINTING_DEVICE_RIGHT
// Pointing device is on the left split.
#undef POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_LEFT
#define POINTING_DEVICE_ENABLE

// #define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y